name: Build, lint, and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repository
        uses: actions/checkout@v3
      - name: Download node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run continuous integration
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'build'
